# Generated by Django 5.1.4 on 2024-12-21 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
