# Generated by Django 5.1.4 on 2024-12-22 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_delete_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
