# Generated by Django 5.1.4 on 2024-12-21 18:00

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_desc',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.CharField(max_length=10),
        ),
    ]
