# Generated by Django 5.1.4 on 2024-12-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_product_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='product_images/default_image.jpg', upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
