# Generated by Django 5.1.4 on 2024-12-21 19:16

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_name', models.CharField(max_length=50)),
                ('review_rev', models.CharField(max_length=50)),
                ('review_star', models.TextField()),
                ('review_desc', tinymce.models.HTMLField()),
                ('review_price', models.CharField(max_length=10)),
                ('review_image', models.ImageField(upload_to='review_images/')),
            ],
        ),
    ]
