# Generated by Django 5.1.4 on 2024-12-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_review_alter_product_product_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product_image',
            field=models.ImageField(upload_to='review_images/'),
        ),
    ]
